# Generated by Django 5.1.6 on 2025-04-04 22:05

import cloudinary.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_callinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10485760)]),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='call_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
