# Generated by Django 5.1.6 on 2025-04-07 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_mediafile_file_extension_mediafile_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('screen_share', 'Screen Share')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ice_config', models.JSONField(blank=True, null=True)),
                ('media_constraints', models.JSONField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_webrtc_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='webrtc_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_sessions', to='communication.room')),
            ],
            options={
                'verbose_name': 'WebRTC Session',
                'verbose_name_plural': 'WebRTC Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCPeerConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('connection_offer', models.TextField(blank=True, null=True)),
                ('connection_answer', models.TextField(blank=True, null=True)),
                ('ice_candidates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_peer_connections', to=settings.AUTH_USER_MODEL)),
                ('remote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_peer_connections', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_connections', to='communication.webrtcsession')),
            ],
            options={
                'verbose_name': 'WebRTC Peer Connection',
                'verbose_name_plural': 'WebRTC Peer Connections',
                'unique_together': {('session', 'local_user', 'remote_user')},
            },
        ),
    ]
