# Generated by Django 5.1.5 on 2025-02-21 06:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(blank=True, max_length=100)),
                ('startup_stage', models.CharField(choices=[('IDEA', 'Idea Stage'), ('MVP', 'MVP'), ('EARLY', 'Early Stage'), ('GROWTH', 'Growth Stage'), ('SCALING', 'Scaling')], default='IDEA', max_length=20)),
                ('pitch', models.TextField(help_text='Elevator pitch for your startup idea', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of your startup')),
                ('role', models.CharField(choices=[('FOUNDER', 'Founder'), ('CO_FOUNDER', 'Co-Founder'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('MARKETER', 'Marketing Specialist'), ('BUSINESS_DEV', 'Business Developer'), ('PRODUCT_MANAGER', 'Product Manager'), ('FINANCIAL_EXPERT', 'Financial Expert'), ('OTHER', 'Other')], max_length=20)),
                ('skills', models.JSONField(default=list, help_text='List of skills and expertise')),
                ('looking_for', models.JSONField(default=list, help_text="Roles/skills you're looking for in potential co-founders")),
                ('pitch_deck', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pitch_deck')),
                ('startup_images', models.JSONField(default=list, help_text='List of Cloudinary URLs for startup images')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('funding_stage', models.CharField(blank=True, max_length=100)),
                ('investment_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='startup_image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.startupprofile')),
            ],
        ),
    ]
