# Generated by Django 5.1.5 on 2025-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='interests',
            field=models.JSONField(default=list, help_text='List of personal and professional interests'),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='profile_images',
            field=models.JSONField(default=list, help_text='List of Cloudinary URLs for profile images'),
        ),
    ]
