# Generated by Django 5.1.6 on 2025-04-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_startupimage_profile_startupidea_and_more'),
        ('myapp', 'fix_duplicate_bio_column'),
    ]

    operations = [
    ]
