# Generated by Django 5.1.6 on 2025-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20250403_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupidea',
            name='looking_for',
            field=models.TextField(blank=True, default='', help_text="Comma-separated list of roles/skills you're looking for"),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of skills and expertise needed for this idea'),
        ),
    ]
