# Generated by Django 5.1.6 on 2025-04-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_startupidea_looking_for_and_more'),
    ]

    operations = [
    ]
