# Generated by Django 5.1.6 on 2025-04-03 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fix_duplicate_bio_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members for this startup idea', related_name='member_startups', to=settings.AUTH_USER_MODEL),
        ),
    ]
