# Generated by Django 5.1.6 on 2025-04-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0002_remove_customuser_phone_number"),
        ("authen", "0003_auto_20250402_1947"),
    ]

    operations = []
