# Generated by Django 5.1.6 on 2025-04-02 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_merge_20250402_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, help_text='Your years of experience', max_length=50, null=True, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, help_text='Your industry or sector', max_length=100, null=True, verbose_name='industry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of your skills', null=True, verbose_name='skills'),
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title (e.g., LinkedIn, GitHub)', max_length=100)),
                ('url', models.URLField(help_text='URL to contact resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
