# Generated by Django X.X on YYYY-MM-DD

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "authen",
            "0005_customuser_experience_customuser_industry_and_more",
        ),  # Replace with actual previous migration
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="career_summary",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="career_summary",
                help_text="A brief overview of your professional journey and career goals",
            ),
        ),
        migrations.CreateModel(
            name="PastProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Project title or name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the project"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "technologies",
                    models.TextField(
                        blank=True,
                        help_text="Technologies or tools used in the project (comma-separated)",
                        null=True,
                    ),
                ),
                (
                    "project_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to project repository or live demo",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_projects",
                        to="authen.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Past Projects",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
    ]
