# Generated by Django 5.1.6 on 2025-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_career_pastproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastproject',
            name='role',
            field=models.CharField(blank=True, help_text='Your role in the project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold')], default='completed', help_text='Current status of the project', max_length=20),
        ),
    ]
