# Generated by Django 5.1.6 on 2025-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_pastproject_role_pastproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastproject',
            name='technologies',
            field=models.CharField(blank=True, help_text='Technologies or tools used in the project (comma-separated)', max_length=500, null=True),
        ),
    ]
