# Generated by Django 5.1.6 on 2025-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_alter_pastproject_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='past_projects',
            field=models.TextField(blank=True, help_text='Comma-separated list of past projects', null=True, verbose_name='past_projects'),
        ),
        migrations.DeleteModel(
            name='PastProject',
        ),
    ]
