FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

WORKDIR /app

RUN python manage.py makemigrations
RUN python manage.py migrate

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "server.asgi:application"]