# POST http://127.0.0.1:8000/api/authen/register/
# Content-Type: application/json

# {
#     "username": "testuser3",
#     "first_name": "testfirst2",
#     "last_name": "testlast2",
#     "email": "test3@gmail.com",
#     "password": "testinga"
# }

POST http://127.0.0.1:8000/api/authen/login/
Content-Type: application/json

{
    "email": "test3@gmail.com",
    "password": "testinga"
}

# GET http://127.0.0.1:8000/api/authen/test-token/
# Content-Type: application/json
# Authorization: Token 61abc658d43ae3c4d97813300fbd3a9a0ce847ef