# Generated by Django 5.1.6 on 2025-04-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
