# Generated by Django 5.1.5 on 2025-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_is_read_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
