name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/trizzlybare/startup-hub:latest
        docker login --username TrizzlyBare --password ${{ secrets.GH_TOKEN }} ghcr.io
        docker push ghcr.io/trizzlybare/startup-hub:latest
