name: CI/CD Pipeline for Windows Server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
      - name: Run migrations
        run: |
          cd server
          python manage.py makemigrations
          python manage.py migrate
      - name: Run tests
        run: |
          cd server
          python manage.py test

  deploy:
    # Use the self-hosted runner that's on the same network as your Windows server
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Since we're running on the same network, we can verify connectivity directly
      - name: Verify server connectivity
        shell: powershell
        run: |
          Write-Host "Testing connectivity to ${{ secrets.SERVER_IP }}"
          $pingResult = Test-Connection -ComputerName ${{ secrets.SERVER_IP }} -Count 4 -Quiet
          if (-not $pingResult) {
            Write-Warning "Cannot ping server, but continuing with deployment"
          } else {
            Write-Host "Server is reachable"
          }
      
      # Build Docker image
      - name: Build Docker image
        shell: powershell
        run: |
          cd server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/startup-hub:latest .
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        shell: powershell
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      # Push image to Docker Hub
      - name: Push image to Docker Hub
        shell: powershell
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/startup-hub:latest
      
      # Deploy using appropriate method for Windows
      - name: Deploy to Windows server
        shell: powershell
        run: |
          # For Windows server, we have several options:
          
          # Option 1: If OpenSSH Server is installed on Windows target
          try {
            Write-Host "Attempting deployment via SSH..."
            # Need to handle password or use SSH keys
            ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "powershell -Command {
              Write-Host 'Connected to Windows server'
              docker pull ${{ secrets.DOCKER_USERNAME }}/startup-hub:latest
              docker stop startup-hub 2>$null
              docker rm startup-hub 2>$null
              docker-compose -f C:/app/docker-compose.yaml up -d
            }"
          }
          catch {
            Write-Warning "SSH deployment failed. Trying alternative method..."
            
            # Option 2: Using PowerShell remoting (requires WinRM setup)
            try {
              $securePassword = ConvertTo-SecureString ${{ secrets.SERVER_PASSWORD }} -AsPlainText -Force
              $cred = New-Object System.Management.Automation.PSCredential (${{ secrets.SERVER_USER }}, $securePassword)
              
              $session = New-PSSession -ComputerName ${{ secrets.SERVER_IP }} -Credential $cred
              
              Invoke-Command -Session $session -ScriptBlock {
                Write-Host "Connected via PowerShell remoting"
                docker pull ${{ secrets.DOCKER_USERNAME }}/startup-hub:latest
                docker stop startup-hub 2>$null
                docker rm startup-hub 2>$null
                docker-compose -f C:/app/docker-compose.yaml up -d
              }
              
              Remove-PSSession $session
            }
            catch {
              Write-Error "Failed to deploy using PowerShell remoting. Please check credentials and WinRM configuration."
              exit 1
            }
          }
      
      # Verify deployment
      - name: Verify deployment
        shell: powershell
        run: |
          try {
            $containerCheck = ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker ps | Select-String 'startup-hub'"
            if ($containerCheck) {
              Write-Host "Container is running successfully"
            } else {
              Write-Warning "Container may not be running. Please check manually."
            }
          }
          catch {
            Write-Warning "Could not verify if container is running. Please check manually."
          }
        continue-on-error: true

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Notify deployment status
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Deployment Status
          SLACK_MESSAGE: |
            Build: ${{ needs.build.result }}
            Deploy: ${{ needs.deploy.result }}
            ${{ needs.deploy.result == 'success' && 'Deployment completed successfully! :rocket:' || 'Deployment failed! :warning:' }}
          SLACK_COLOR: ${{ needs.deploy.result == 'success' && 'good' || 'danger' }}
        continue-on-error: true
